
version: "3"

services:
    api_huggy_tecnico:
        build: .
        image: micks/api_huggy_tecnico:1.0
        container_name: api_huggy_tecnico
        network_mode: bridge
        env_file:
            - ./.env
        ports:
            - '8105:8105'
            - '8106:8106'
        tty: true
        restart: always
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - /var/lib/letsencrypt:/var/lib/letsencrypt
        environment:        
            - TZ=America/Fortaleza
